# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\LBJ\Documents\Projects\FTP-CLient/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 641)
        MainWindow.setMinimumSize(QtCore.QSize(960, 641))
        MainWindow.setMaximumSize(QtCore.QSize(960, 641))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hostnameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostnameEdit.setGeometry(QtCore.QRect(60, 20, 181, 20))
        self.hostnameEdit.setText("")
        self.hostnameEdit.setObjectName("hostnameEdit")
        self.portBox = QtWidgets.QSpinBox(self.centralwidget)
        self.portBox.setGeometry(QtCore.QRect(285, 20, 61, 22))
        self.portBox.setMinimum(1)
        self.portBox.setMaximum(65535)
        self.portBox.setProperty("value", 21)
        self.portBox.setObjectName("portBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 31, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 61, 20))
        self.label_3.setObjectName("label_3")
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameEdit.setGeometry(QtCore.QRect(90, 50, 151, 20))
        self.usernameEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.usernameEdit.setDragEnabled(False)
        self.usernameEdit.setReadOnly(True)
        self.usernameEdit.setObjectName("usernameEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 50, 61, 20))
        self.label_4.setObjectName("label_4")
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordEdit.setGeometry(QtCore.QRect(320, 50, 161, 20))
        self.passwordEdit.setText("")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setClearButtonEnabled(False)
        self.passwordEdit.setObjectName("passwordEdit")
        self.anymsBox = QtWidgets.QCheckBox(self.centralwidget)
        self.anymsBox.setGeometry(QtCore.QRect(500, 50, 91, 20))
        self.anymsBox.setChecked(True)
        self.anymsBox.setTristate(False)
        self.anymsBox.setObjectName("anymsBox")
        self.putButton = QtWidgets.QPushButton(self.centralwidget)
        self.putButton.setGeometry(QtCore.QRect(460, 290, 41, 23))
        self.putButton.setObjectName("putButton")
        self.getButton = QtWidgets.QPushButton(self.centralwidget)
        self.getButton.setGeometry(QtCore.QRect(460, 330, 41, 23))
        self.getButton.setObjectName("getButton")
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setGeometry(QtCore.QRect(864, 20, 81, 23))
        self.connectButton.setObjectName("connectButton")
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setGeometry(QtCore.QRect(864, 50, 81, 23))
        self.disconnectButton.setObjectName("disconnectButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 54, 23))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(520, 100, 71, 23))
        self.label_6.setObjectName("label_6")
        self.localdirEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.localdirEdit.setGeometry(QtCore.QRect(80, 100, 251, 23))
        self.localdirEdit.setReadOnly(True)
        self.localdirEdit.setObjectName("localdirEdit")
        self.localdirButton = QtWidgets.QPushButton(self.centralwidget)
        self.localdirButton.setGeometry(QtCore.QRect(370, 100, 70, 23))
        self.localdirButton.setObjectName("localdirButton")
        self.remotedirEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.remotedirEdit.setGeometry(QtCore.QRect(600, 100, 231, 23))
        self.remotedirEdit.setReadOnly(False)
        self.remotedirEdit.setObjectName("remotedirEdit")
        self.remotedirButton = QtWidgets.QPushButton(self.centralwidget)
        self.remotedirButton.setGeometry(QtCore.QRect(870, 100, 70, 23))
        self.remotedirButton.setObjectName("remotedirButton")
        self.portButton = QtWidgets.QRadioButton(self.centralwidget)
        self.portButton.setGeometry(QtCore.QRect(470, 20, 61, 20))
        self.portButton.setChecked(True)
        self.portButton.setObjectName("portButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 20, 91, 20))
        self.label_7.setObjectName("label_7")
        self.pasvButton = QtWidgets.QRadioButton(self.centralwidget)
        self.pasvButton.setGeometry(QtCore.QRect(530, 20, 51, 20))
        self.pasvButton.setObjectName("pasvButton")
        self.remoteView = QtWidgets.QTreeView(self.centralwidget)
        self.remoteView.setGeometry(QtCore.QRect(519, 130, 421, 481))
        self.remoteView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.remoteView.setRootIsDecorated(False)
        self.remoteView.setSortingEnabled(True)
        self.remoteView.setObjectName("remoteView")
        self.localView = QtWidgets.QTreeView(self.centralwidget)
        self.localView.setGeometry(QtCore.QRect(20, 130, 421, 481))
        self.localView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.localView.setRootIsDecorated(False)
        self.localView.setSortingEnabled(True)
        self.localView.setObjectName("localView")
        self.remoteupButton = QtWidgets.QPushButton(self.centralwidget)
        self.remoteupButton.setGeometry(QtCore.QRect(840, 100, 23, 23))
        self.remoteupButton.setObjectName("remoteupButton")
        self.localupButton = QtWidgets.QPushButton(self.centralwidget)
        self.localupButton.setGeometry(QtCore.QRect(340, 100, 23, 23))
        self.localupButton.setObjectName("localupButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FTP Client"))
        self.label.setText(_translate("MainWindow", "Host:"))
        self.label_2.setText(_translate("MainWindow", "Port: "))
        self.label_3.setText(_translate("MainWindow", "Username:"))
        self.usernameEdit.setText(_translate("MainWindow", "anonymous"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.anymsBox.setText(_translate("MainWindow", "Anonymous"))
        self.putButton.setText(_translate("MainWindow", "→"))
        self.getButton.setText(_translate("MainWindow", "←"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.label_5.setText(_translate("MainWindow", "Local dir:"))
        self.label_6.setText(_translate("MainWindow", "Remote Dir:"))
        self.localdirButton.setText(_translate("MainWindow", "Open"))
        self.remotedirButton.setText(_translate("MainWindow", "Open"))
        self.portButton.setText(_translate("MainWindow", "PORT"))
        self.label_7.setText(_translate("MainWindow", "Transfer mode:"))
        self.pasvButton.setText(_translate("MainWindow", "PASV"))
        self.remoteupButton.setText(_translate("MainWindow", "↑"))
        self.localupButton.setText(_translate("MainWindow", "↑"))
import icon_rc
